name: Deploy

on:
  push:
    branches:
      - UAT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Save SSH Key
        run: |
          echo "${{ secrets.SSHKEY }}" > private_key
          chmod 600 private_key

      - name: Test SSH Connection
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} exit

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/html/adminUATMadhav/sprintnxtadminbackenduat
            git config --global --add safe.directory /var/www/html/adminUATMadhav/sprintnxtadminbackenduat
            git stash
            git pull origin UAT
            git stash pop
            chmod +x ./.scripts/deploy.sh
            ./.scripts/deploy.sh
          debug: true
