name: Deploy

# Trigger the workflow on pushes to the UAT branch
on:
  push:
    branches:
      - UAT

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check VPN Connection and Server Reachability
        run: |
          # Check if the server is reachable (requires VPN)
          if ! ping -c 3 10.50.2.185; then
            echo "VPN is not active or server is unreachable. Exiting."
            exit 1
          fi
          echo "Server is reachable. Proceeding with deployment."

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/html/adminUATMadhav/sprintnxtadminbackenduat
            git config --global --add safe.directory /var/www/html/adminUATMadhav/sprintnxtadminbackenduat
            git stash
            sudo git pull origin UAT
            git stash pop
            sudo chmod +x ./.scripts/deploy.sh
            sudo ./.scripts/deploy.sh
          debug: true
